version: '2.4'

services:
    #### pingpong service ####
    pingpong_csharp:
        build: ./src
        image: pingpong_csharp:1.3.0
        restart: unless-stopped
        mem_limit: 100mb
        networks:
            - proxy-redirect
        environment:
            - TOPIC_1=topic1
            - TOPIC_2=topic2
            - MQTT_IP=ie-databus
            - MQTT_USER=edge
            - MQTT_PASSWORD=edge
        volumes:
            - './publish/:/publish/'
            - './cfg-data/:/cfg-data/'
    
networks:
  proxy-redirect:
      external:
          name: proxy-redirect
